# Generated by Django 3.1.6 on 2021-02-27 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('red', '0003_auto_20210227_2101'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensaje',
            name='delete',
            field=models.BooleanField(default=False),
        ),
    ]
